taskmanagement/api/urls.py
from django.urls import path

from api import views

app_name = 'api'


# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined
# url patterns for task list, create, update & delete tasks in separate API endpoints.
# Each endpoint has its own ui page with bootstrap and html, CSS.
urlpatterns = [
    path('tasks/', views.ListView.as_view(), name='list'),
    path('tasks/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('tasks/<int:pk>/status',
         views.StatusDetail.as_view(), name='status'),
]

taskmanagement/task/urls.py
from django.urls import include, path, reverse_lazy

from task import views

app_name = 'tasks'


# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined
# url patterns for task list, create, update & delete tasks in separate API endpoints.
# Each endpoint has its own ui page with bootstrap and html, CSS.
urlpatterns = [
    path('', views.TaskListView.as_view(), name='all'),
    path('create',
         views.TaskCreateView.as_view(success_url=reverse_lazy('tasks:all')), name='task_create'),
    path('<int:pk>/', views.TaskDetailView.as_view(), name='task_detail'),
    path('<int:pk>/update',
         views.TaskUpdateView.as_view(success_url=reverse_lazy('tasks:all')), name='task_update'),
    path('<int:pk>/delete',
         views.TaskDeleteView.as_view(success_url=reverse_lazy('tasks:all')), name='task_delete'),
    path('<int:pk>/status',
         views.StatusCreateView.as_view(), name='status_updated'),
]


taskmanagement/taskmanagement/urls.py
from django.contrib import admin
from django.urls import path, include

# Here home, default login, task url patterns has been defined.
urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('tasks/', include('task.urls')),
    path('api/', include('api.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

taskmanagement/api/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings


# First model definition
class Task(models.Model):
    # Mandatory title field
    title = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    )
    # Mandatory desc field
    description = models.TextField()
    # Mandatory owner field
    owner = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    # optional story point field
    story_point = models.PositiveSmallIntegerField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        return '%s : %s' % (self.title, self.description)


# Second model definition with predefined choices.
class Status(models.Model):
    # The status parameters are predefined and had been implemented in  server-side.
    # In order to view meaningful status to user in detail page, I haven't used integers/abbreviation.
    status_list = (
        ('Open', 'Open'),
        ('InProgress', 'In progress'),
        ('Review', 'Review'),
        ('Test', 'Test'),
        ('Done', 'Done'),
    )
    # with defining choices, we can have a dropdown menu in ui page with predefined status options.
    status = models.CharField(max_length=20, choices=status_list, default=0)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        return self.status

taskmanagement/task/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.humanize.templatetags.humanize import naturaltime
from django.db.models import Q

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.renderers import TemplateHTMLRenderer

from api.models import Task, Status
from api.serializers import TaskSerializer, StatusSerializer


# Task list view
class TaskListView(APIView):
    queryset = Task.objects.all()
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'task/list.html'

    def get(self, request):
        # search query handling
        strval = request.GET.get("search", False)
        if strval:
            # Multi-field search
            # __icontains for case-insensitive search
            query = Q(title__icontains=strval)
            query.add(Q(description__icontains=strval), Q.OR)
            tasks = (Task.objects.filter(query)).select_related().order_by('-updated_at')[:10]
        else:
            tasks = Task.objects.all().order_by('-updated_at')[:10]
        for obj in tasks:
            obj.natural_updated = naturaltime(obj.updated_at)
        ctx = {'task_list': tasks, 'search': strval}
        return Response(ctx)


# Task detail view
class TaskDetailView(APIView):
    queryset = Task.objects.all()
    renderer_classes = [TemplateHTMLRenderer]
    serializer_class = TaskSerializer
    template_name = "task/detail.html"

    def get(self, request, pk):
        task = get_object_or_404(Task, id=pk)
        status_list = Status.objects.filter(task=task).order_by('-updated_at')
        status_serializer = StatusSerializer()
        ctx = {'task': task, 'status_list': status_list, 'status_serializer': status_serializer,
               "choices": Status.status_list}
        return Response(ctx)


# Create task view
class TaskCreateView(LoginRequiredMixin, APIView):
    queryset = Task.objects.all()
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'task/task_create.html'
    success_url = reverse_lazy('tasks:all')

    def get(self, request, pk=None):
        serializer = TaskSerializer()
        ctx = {'serializer': serializer}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        serializer = TaskSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save(owner=request.user)
            return redirect(self.success_url)
        ctx = {'serializer': serializer}
        return render(request, self.template_name, ctx)


# Update task view
class TaskUpdateView(LoginRequiredMixin, APIView):
    queryset = Task.objects.all()
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'task/task_create.html'
    success_url = reverse_lazy('tasks:all')

    def get(self, request, pk):
        task = get_object_or_404(Task, id=pk, owner=self.request.user)
        serializer = TaskSerializer(instance=task)
        ctx = {'serializer': serializer}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        task = get_object_or_404(Task, id=pk, owner=self.request.user)
        serializer = TaskSerializer(data=request.data, instance=task)
        if serializer.is_valid():
            serializer.save(owner=request.user)
            return redirect(self.success_url)
        ctx = {'serializer': serializer}
        return render(request, self.template_name, ctx)


# Delete task view
class TaskDeleteView(LoginRequiredMixin, APIView):
    queryset = Task.objects.all()
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'task/task_delete.html'
    success_url = reverse_lazy('tasks:all')

    def get(self, request, pk):
        task = get_object_or_404(Task, id=pk, owner=self.request.user)
        ctx = {'task': task}
        return render(request, self.template_name, ctx)

    def post(self, request, pk):
        task = get_object_or_404(Task, id=pk, owner=self.request.user)
        task.delete()
        return redirect(self.success_url)


# Status view
class StatusCreateView(LoginRequiredMixin, APIView):
    queryset = Status.objects.all()

    def get(self, request, pk):
        return redirect(reverse('tasks:task_detail', args=[pk]))

    def post(self, request, pk):
        t = get_object_or_404(Task, id=pk)
        s = request.POST.get('status')
        status = Status(status=s, task=t, owner=request.user)
        status.save()
        return redirect(reverse('tasks:task_detail', args=[t.id]))

taskmanagement/task/templates/task/detail.html
{% extends "base_menu.html" %}
{% block content %}
<span style="float: right;">
  ({{ task.updated_at }})
  {% if task.owner == user %}
    <a href="{% url 'tasks:task_update' task.id %}"><i class="fa fa-pencil"></i></a>
    <a href="{% url 'tasks:task_delete' task.id %}"><i class="fa fa-trash"></i></a>
  {% endif %}
</span>
<h1>{{ task.title }}</h1>
<p>
  <strong> Description: </strong> {{ task.description }}
</p>
<p>
  <strong> Story Point: </strong> {{ task.story_point }}
</p>
<p>
  (Last Updated: {{ task.updated_at }})
</p>
<br>
</br>
{% if task.owner == user %}
  <p>
    <strong> Status: </strong>
  </p>
  <form method="post" action="{% url 'tasks:status_updated' task.id %}">
    {% csrf_token %}
    <select class="dropdown" name="status">
      {% for key, choice in choices %}
        <option value="{{ choice }}">{{ choice }}</option>
      {% endfor %}
    </select>
    <br>
    </br>
    <p>
      <input type="submit" value="Submit">
      <input type="submit" value="All Tasks" onclick="window.location.href='{% url 'tasks:all' %}';return false;">
    </p>
  </form>
{% endif %}
{% if user.is_authenticated %}
{% for status in status_list %}
  <p> {{ status.status }}
      ({{ status.updated_at }})
  </p>
{% endfor %}
{% endif %}
{% endblock %}

taskmanagement/task/templates/task/list.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Tasks</h1>
<div style="float:right">
<!-- https://www.w3schools.com/howto/howto_css_search_button.asp -->
<form>
  <input type="text" placeholder="Search.." name="search"
  {% if search %} value="{{ search }}" {% endif %}
  >
  <button type="submit"><i class="fa fa-search"></i></button>
<a href="{% url 'tasks:all' %}"><i class="fa fa-undo"></i></a>
</form>
</div>
<p>
{% if task_list %}
<ul>
  {% for task in task_list %}
    <li>
      <a href="{% url 'tasks:task_detail'  task.id %}">{{ task.title }}</a>
      {% if task.owner == user %}
        (<a href="{% url 'tasks:task_update' task.id %}">Edit</a> |
        <a href="{% url 'tasks:task_delete' task.id %}">Delete</a>)
      {% endif %}
    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no task in the database.</p>
{% endif %}
</p>
<p>
<a href="{% url 'tasks:task_create' %}">Add a Task</a> |
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'tasks:all' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'tasks:all' %}">Login</a>
{% endif %}
</p>
{% endblock %}

taskmanagement/task/templates/task/task_create.html
{% extends "base_menu.html" %}
{% load rest_framework %}
{% block content %}

<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {% render_form serializer template_pack='rest_framework/vertical' %}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'tasks:all' %}';return false;">
  </form>
</p>
{% endblock %}

taskmanagement/task/templates/task/task_delete.html
{% extends "base_menu.html" %}
{% block content %}
{% if task.owner == user %}
<h1>Delete Task</h1>

<p>Are you sure you want to delete the task: {{task.title}}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% else %}
  <p>You don't have permission to delete this task!</p>
 <input type="submit" value="All Tasks" onclick="window.location.href='{% url 'tasks:all' %}';return false;">
{% endif %}
{% endblock %}